-- Employee Payroll Database
-- Create Departments Table
CREATE TABLE Departments (
    Dept_ID      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Dept_Name    VARCHAR2(100) NOT NULL,
    Location     VARCHAR2(100)
);

-- Create Employees Table
CREATE TABLE Employees (
    Emp_ID       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    First_Name   VARCHAR2(50),
    Last_Name    VARCHAR2(50),
    Gender       VARCHAR2(10),
    DOB          DATE,
    Join_Date    DATE,
    Dept_ID      NUMBER REFERENCES Departments(Dept_ID),
    Email        VARCHAR2(100) UNIQUE,
    Phone        VARCHAR2(20),
    Job_Title    VARCHAR2(50),
    Status       VARCHAR2(20) DEFAULT 'Active'
);

-- Create Salaries Table
CREATE TABLE Salaries (
    Salary_ID    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Emp_ID       NUMBER REFERENCES Employees(Emp_ID),
    Basic_Pay    NUMBER(10,2),
    HRA          NUMBER(10,2),
    DA           NUMBER(10,2),
    Other_Allowances NUMBER(10,2),
    Effective_From DATE,
    Effective_To   DATE
);

-- Create Attendance Table
CREATE TABLE Attendance (
    Att_ID       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Emp_ID       NUMBER REFERENCES Employees(Emp_ID),
    Att_Date     DATE,
    Status       VARCHAR2(20) CHECK (Status IN ('Present', 'Absent', 'Leave', 'Holiday'))
);

-- Create Leaves Table
CREATE TABLE Leaves (
    Leave_ID     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Emp_ID       NUMBER REFERENCES Employees(Emp_ID),
    Leave_Date   DATE,
    Leave_Type   VARCHAR2(30),
    Reason       VARCHAR2(200),
    Approved_By  NUMBER REFERENCES Employees(Emp_ID)
);

-- Create Deductions Table
CREATE TABLE Deductions (
    Deduction_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Emp_ID       NUMBER REFERENCES Employees(Emp_ID),
    Deduction_Type VARCHAR2(50),
    Amount       NUMBER(10,2),
    Deduction_Date DATE
);

-- Create Payroll Table
CREATE TABLE Payroll (
    Payroll_ID   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Emp_ID       NUMBER REFERENCES Employees(Emp_ID),
    Pay_Period   VARCHAR2(20), -- e.g., 'May-2025'
    Gross_Salary NUMBER(10,2),
    Total_Deductions NUMBER(10,2),
    Net_Pay      NUMBER(10,2),
    Pay_Date     DATE
);